

objects = $(wildcard *.o)

# test_args_option:

# test_args_option.o: test_args_option.c
# 	gcc -c test_args_option.c

# .PHONY : clean

# clean:


foo = $(bar)
bar = $(ugh)
ugh = Huh?
all:
	echo $(foo)
